version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "8000:8080"
    environment:
      - PORT=8080
      - CATALOG_URL=http://catalog:8080
      - STREAMING_URL=http://streaming:8080
    depends_on:
      - catalog
      - streaming
    networks:
      - video-streaming

  catalog:
    build:
      context: ./apps/video-catalog-service
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
    volumes:
      - ./apps/streaming-service/videos_dash:/videos_dash:ro
    networks:
      - video-streaming

  streaming:
    build:
      context: ./apps/streaming-service
      dockerfile: Dockerfile
    ports:
      - "8081:8080"
    environment:
      - PORT=8080
    volumes:
      - ./apps/streaming-service/videos:/root/videos:ro
      - ./apps/streaming-service/videos_dash:/root/videos_dash:ro
    networks:
      - video-streaming

networks:
  video-streaming:
    driver: bridge
